-- Auto-generated from KH3 Archipelago

ITEM_MAPPING_BY_NAME = {
    ["Ability: Aerial Dive"] = { code = "ability_aerial_dive", type = "toggle" },
    ["Ability: Aerial Sweep"] = { code = "ability_aerial_sweep", type = "toggle" },
    ["Ability: Aeroza"] = { code = "ability_aeroza", type = "toggle" },
    ["Ability: Aero Syphon"] = { code = "ability_aero_syphon", type = "toggle" },
    ["Ability: Aero Boost"] = { code = "ability_aero_boost", type = "toggle" },
    ["Ability: Air Combo Plus"] = { code = "ability_air_combo_plus", type = "toggle" },
    ["Ability: Air Combo Boost"] = { code = "ability_air_combo_boost", type = "toggle" },
    ["Ability: Aerial Dodge"] = { code = "ability_aerial_dodge", type = "toggle" },
    ["Ability: Air Slide"] = { code = "ability_air_slide", type = "toggle" },
    ["Ability: Falling Slash"] = { code = "ability_falling_slash", type = "toggle" },
    ["Ability: Aerial Recovery"] = { code = "ability_aerial_recovery", type = "toggle" },
    ["Ability: Groundbreaker"] = { code = "ability_groundbreaker", type = "toggle" },
    ["Ability: Attraction Extender"] = { code = "ability_attraction_extender", type = "toggle" },
    ["Ability: Attraction Enhancer"] = { code = "ability_attraction_enhancer", type = "toggle" },
    ["Ability: Auto-Finish"] = { code = "ability_auto_finish", type = "toggle" },
    ["Ability: Magic Lock-On"] = { code = "ability_magic_lock_on", type = "toggle" },
    ["Ability: Frontline Photographer"] = { code = "ability_frontline_photographer", type = "toggle" },
    ["Ability: Top Condition"] = { code = "ability_top_condition", type = "toggle" },
    ["Ability: Blizzaza"] = { code = "ability_blizzaza", type = "toggle" },
    ["Ability: Blizzard Syphon"] = { code = "ability_blizzard_syphon", type = "toggle" },
    ["Ability: Blizzard Boost"] = { code = "ability_blizzard_boost", type = "toggle" },
    ["Ability: Payback Strike"] = { code = "ability_payback_strike", type = "toggle" },
    ["Ability: Burn Protection"] = { code = "ability_burn_protection", type = "toggle" },
    ["Ability: Berserk Charge"] = { code = "ability_berserk_charge", type = "toggle" },
    ["Ability: Triple Rush"] = { code = "ability_triple_rush", type = "toggle" },
    ["Ability: Chef Extraordinaire"] = { code = "ability_chef_extraordinaire", type = "toggle" },
    ["Ability: Cloud Protection"] = { code = "ability_cloud_protection", type = "toggle" },
    ["Ability: Withstand Combo"] = { code = "ability_withstand_combo", type = "toggle" },
    ["Ability: Combo Master"] = { code = "ability_combo_master", type = "toggle" },
    ["Ability: Combo Plus"] = { code = "ability_combo_plus", type = "toggle" },
    ["Ability: Combo Boost"] = { code = "ability_combo_boost", type = "toggle" },
    ["Ability: Reprisal Boost"] = { code = "ability_reprisal_boost", type = "toggle" },
    ["Ability: Critical Recharge"] = { code = "ability_critical_recharge", type = "toggle" },
    ["Ability: Critical Converter"] = { code = "ability_critical_converter", type = "toggle" },
    ["Ability: Critical Counter"] = { code = "ability_critical_counter", type = "toggle" },
    ["Ability: Damage Control"] = { code = "ability_damage_control", type = "toggle" },
    ["Ability: Curaza"] = { code = "ability_curaza", type = "toggle" },
    ["Ability: Damage Syphon"] = { code = "ability_damage_syphon", type = "toggle" },
    ["Ability: Dark Syphon"] = { code = "ability_dark_syphon", type = "toggle" },
    ["Ability: Defender"] = { code = "ability_defender", type = "toggle" },
    ["Ability: Electric Protection"] = { code = "ability_electric_protection", type = "toggle" },
    ["Ability: Dodge Roll"] = { code = "ability_dodge_roll", type = "toggle" },
    ["Ability: Doubleflight"] = { code = "ability_doubleflight", type = "toggle" },
    ["Ability: Endless Magic"] = { code = "ability_endless_magic", type = "toggle" },
    ["Ability: Zero EXP"] = { code = "ability_zero_exp", type = "toggle" },
    ["Ability: EXP Incentive"] = { code = "ability_exp_incentive", type = "toggle" },
    ["Ability: Last Charge"] = { code = "ability_last_charge", type = "toggle" },
    ["Ability: Firaza"] = { code = "ability_firaza", type = "toggle" },
    ["Ability: Fire Syphon"] = { code = "ability_fire_syphon", type = "toggle" },
    ["Ability: Fire Boost"] = { code = "ability_fire_boost", type = "toggle" },
    ["Ability: Flash Step"] = { code = "ability_flash_step", type = "toggle" },
    ["Ability: Focus Syphon"] = { code = "ability_focus_syphon", type = "toggle" },
    ["Ability: Formchange Extender"] = { code = "ability_formchange_extender", type = "toggle" },
    ["Ability: Situation Boost"] = { code = "ability_situation_boost", type = "toggle" },
    ["Ability: Focus Converter"] = { code = "ability_focus_converter", type = "toggle" },
    ["Ability: Freeze Protection"] = { code = "ability_freeze_protection", type = "toggle" },
    ["Ability: Assist Friends"] = { code = "ability_assist_friends", type = "toggle" },
    ["Ability: Full MP Blast"] = { code = "ability_full_mp_blast", type = "toggle" },
    ["Ability: Fusion Rocket"] = { code = "ability_fusion_rocket", type = "toggle" },
    ["Ability: Fusion Spin"] = { code = "ability_fusion_spin", type = "toggle" },
    ["Ability: Glide"] = { code = "ability_glide", type = "toggle" },
    ["Ability: More Grand Magic"] = { code = "ability_more_grand_magic", type = "toggle" },
    ["Ability: Counter Slash"] = { code = "ability_counter_slash", type = "toggle" },
    ["Ability: Block Replenisher"] = { code = "ability_block_replenisher", type = "toggle" },
    ["Ability: Harvester"] = { code = "ability_harvester", type = "toggle" },
    ["Ability: High Jump"] = { code = "ability_high_jump", type = "toggle" },
    ["Ability: HP Converter"] = { code = "ability_hp_converter", type = "toggle" },
    ["Ability: Item Boost"] = { code = "ability_item_boost", type = "toggle" },
    ["Ability: Second Chance"] = { code = "ability_second_chance", type = "toggle" },
    ["Ability: Leaf Bracer"] = { code = "ability_leaf_bracer", type = "toggle" },
    ["Ability: Scan"] = { code = "ability_scan", type = "toggle" },
    ["Ability: Link Extender"] = { code = "ability_link_extender", type = "toggle" },
    ["Ability: Lucky Strike"] = { code = "ability_lucky_strike", type = "toggle" },
    ["Ability: Cuisine Extender"] = { code = "ability_cuisine_extender", type = "toggle" },
    ["Ability: Magic Flash"] = { code = "ability_magic_flash", type = "toggle" },
    ["Ability: Magic Combo Thrift"] = { code = "ability_magic_combo_thrift", type = "toggle" },
    ["Ability: Magic Galvanizer"] = { code = "ability_magic_galvanizer", type = "toggle" },
    ["Ability: Magic Treasure Magnet"] = { code = "ability_magic_treasure_magnet", type = "toggle" },
    ["Ability: Magic Roulette"] = { code = "ability_magic_roulette", type = "toggle" },
    ["Ability: Grand Magic Extender"] = { code = "ability_grand_magic_extender", type = "toggle" },
    ["Ability: Master Treasure Magnet"] = { code = "ability_master_treasure_magnet", type = "toggle" },
    ["Ability: Rags to Riches"] = { code = "ability_rags_to_riches", type = "toggle" },
    ["Ability: MP Converter"] = { code = "ability_mp_converter", type = "toggle" },
    ["Ability: MP Haste"] = { code = "ability_mp_haste", type = "toggle" },
    ["Ability: MP Hastega"] = { code = "ability_mp_hastega", type = "toggle" },
    ["Ability: MP Hastera"] = { code = "ability_mp_hastera", type = "toggle" },
    ["Ability: Extra Cast"] = { code = "ability_extra_cast", type = "toggle" },
    ["Ability: MP Safety"] = { code = "ability_mp_safety", type = "toggle" },
    ["Ability: MP Thrift"] = { code = "ability_mp_thrift", type = "toggle" },
    ["Ability: Munny Converter"] = { code = "ability_munny_converter", type = "toggle" },
    ["Ability: Overtime"] = { code = "ability_overtime", type = "toggle" },
    ["Ability: Pole Spin"] = { code = "ability_pole_spin", type = "toggle" },
    ["Ability: Pole Swing"] = { code = "ability_pole_swing", type = "toggle" },
    ["Ability: Cure Converter"] = { code = "ability_cure_converter", type = "toggle" },
    ["Ability: Hearty Meal"] = { code = "ability_hearty_meal", type = "toggle" },
    ["Ability: Treasure Magnet"] = { code = "ability_treasure_magnet", type = "toggle" },
    ["Ability: Prize Proliferator"] = { code = "ability_prize_proliferator", type = "toggle" },
    ["Ability: Quick Slash"] = { code = "ability_quick_slash", type = "toggle" },
    ["Ability: Radial Blaster"] = { code = "ability_radial_blaster", type = "toggle" },
    ["Ability: Block"] = { code = "ability_block", type = "toggle" },
    ["Ability: Counter Kick"] = { code = "ability_counter_kick", type = "toggle" },
    ["Ability: Counter Impact"] = { code = "ability_counter_impact", type = "toggle" },
    ["Ability: Final Blow"] = { code = "ability_final_blow", type = "toggle" },
    ["Ability: Risk Dodge"] = { code = "ability_risk_dodge", type = "toggle" },
    ["Ability: Rising Spiral"] = { code = "ability_rising_spiral", type = "toggle" },
    ["Ability: Sneeze Protection"] = { code = "ability_sneeze_protection", type = "toggle" },
    ["Ability: Sonic Cleave"] = { code = "ability_sonic_cleave", type = "toggle" },
    ["Ability: Sonic Slash"] = { code = "ability_sonic_slash", type = "toggle" },
    ["Ability: Stun Protection"] = { code = "ability_stun_protection", type = "toggle" },
    ["Ability: Somersault"] = { code = "ability_somersault", type = "toggle" },
    ["Ability: Superjump"] = { code = "ability_superjump", type = "toggle" },
    ["Ability: Superslide"] = { code = "ability_superslide", type = "toggle" },
    ["Ability: Thundaza"] = { code = "ability_thundaza", type = "toggle" },
    ["Ability: Thunder Syphon"] = { code = "ability_thunder_syphon", type = "toggle" },
    ["Ability: Thunder Boost"] = { code = "ability_thunder_boost", type = "toggle" },
    ["Ability: Speed Slash"] = { code = "ability_speed_slash", type = "toggle" },
    ["Ability: Buzz Saw"] = { code = "ability_buzz_saw", type = "toggle" },
    ["Ability: Unison Blizzard"] = { code = "ability_unison_blizzard", type = "toggle" },
    ["Ability: Unison Fire"] = { code = "ability_unison_fire", type = "toggle" },
    ["Ability: Unison Thunder"] = { code = "ability_unison_thunder", type = "toggle" },
    ["Ability: HP Walker"] = { code = "ability_hp_walker", type = "toggle" },
    ["Ability: MP Walker"] = { code = "ability_mp_walker", type = "toggle" },
    ["Ability: Wall Kick"] = { code = "ability_wall_kick", type = "toggle" },
    ["Ability: Waterza"] = { code = "ability_waterza", type = "toggle" },
    ["Ability: Water Syphon"] = { code = "ability_water_syphon", type = "toggle" },
    ["Ability: Water Boost"] = { code = "ability_water_boost", type = "toggle" },
    ["Ability: Wizard's Ruse"] = { code = "ability_wizard's_ruse", type = "toggle" },
    ["Bonus: Accessory Slot +1"] = { code = "bonus_accessory_slot_plus1", type = "consumable" },
    ["Bonus: Armor Slot +1"] = { code = "bonus_armor_slot_plus1", type = "consumable" },
    ["Bonus: HP +10"] = { code = "hp_boost", type = "consumable" },
    ["Bonus: HP +5"] = { code = "hp_boost", type = "consumable" },
    ["Bonus: Item Slot +1"] = { code = "bonus_item_slot_plus1", type = "consumable" },
    ["Bonus: MP +3"] = { code = "mp_boost", type = "consumable" },
    ["Bonus: MP +5"] = { code = "mp_boost", type = "consumable" },
    ["Gummiphone"] = { code = "gummiphone", type = "toggle" },
    ["Dream Heartbinder"] = { code = "dream_heartbinder", type = "toggle" },
    ["Pixel Heartbinder"] = { code = "pixel_heartbinder", type = "toggle" },
    ["'Ohana Heartbinder"] = { code = "ohana_heartbinder", type = "toggle" },
    ["Pride Heartbinder"] = { code = "pride_heartbinder", type = "toggle" },
    ["Ocean Heartbinder"] = { code = "ocean_heartbinder", type = "toggle" },
    ["Proof of Fantasy"] = { code = "proof_of_fantasy", type = "toggle" },
    ["Proof of Promises"] = { code = "proof_of_promises", type = "toggle" },
    ["Proof of Times Past"] = { code = "proof_of_times_past", type = "toggle" },
    ["Heart Piece"] = { code = "heart_piece", type = "consumable" },
    ["Magic: Aero"] = { code = "aero", type = "progressive" },
    ["Magic: Blizzard"] = { code = "blizzard", type = "progressive" },
    ["Magic: Cure"] = { code = "cure", type = "progressive" },
    ["Magic: Fire"] = { code = "fire", type = "progressive" },
    ["Magic: Thunder"] = { code = "thunder", type = "progressive" },
    ["Magic: Water"] = { code = "water", type = "progressive" },
    ["Map: The Stairway to the Sky"] = { code = "map_the_stairway_to_the_sky", type = "toggle" },
    ["Map: Breezy Quarter"] = { code = "map_breezy_quarter", type = "toggle" },
    ["Map: The City"] = { code = "map_the_city", type = "toggle" },
    ["Map: Port Royal Waters"] = { code = "map_port_royal_waters", type = "toggle" },
    ["Map: Isla de los Mastiles"] = { code = "map_isla_de_los_mastiles", type = "toggle" },
    ["Map: Ship's End"] = { code = "map_ships_end", type = "toggle" },
    ["Map: Huddled Isles"] = { code = "map_huddled_isles", type = "toggle" },
    ["Map: Sandbar Isle"] = { code = "map_sandbar_isle", type = "toggle" },
    ["Map: The North Mountain"] = { code = "map_the_north_mountain", type = "toggle" },
    ["Map: The Labyrinth of Ice"] = { code = "map_the_labyrinth_of_ice", type = "toggle" },
    ["Map: Realm of the Gods"] = { code = "map_realm_of_the_gods", type = "toggle" },
    ["Map: Mount Olympus"] = { code = "map_mount_olympus", type = "toggle" },
    ["Map: Thebes"] = { code = "map_thebes", type = "toggle" },
    ["Map: The Badlands"] = { code = "map_the_badlands", type = "toggle" },
    ["Map: The Skein of Severance"] = { code = "map_the_skein_of_severance", type = "toggle" },
    ["Map: Monsters, Inc."] = { code = "map_monsters_inc.", type = "toggle" },
    ["Map: The Factory"] = { code = "map_the_factory", type = "toggle" },
    ["Map: The Forest"] = { code = "map_the_forest", type = "toggle" },
    ["Map: The Marsh"] = { code = "map_the_marsh", type = "toggle" },
    ["Map: Andy's House"] = { code = "map_andys_house", type = "toggle" },
    ["Map: Galaxy Toys"] = { code = "map_galaxy_toys", type = "toggle" },
    ["Map: The Neighborhood"] = { code = "map_the_neighborhood", type = "toggle" },
    ["Secret Report 1"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 2"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 3"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 4"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 5"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 6"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 7"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 8"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 9"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 10"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 11"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 12"] = { code = "secret_report", type = "consumable" },
    ["Secret Report 13"] = { code = "secret_report", type = "consumable" },
}