Tracker:AddLocations("locations/overworld.json")
Tracker:AddLocations("locations/olympus_chests.json")
Tracker:AddLocations("locations/olympus_events.json")
Tracker:AddLocations("locations/twilight_town_chests.json")
Tracker:AddLocations("locations/twilight_town_events.json")
Tracker:AddLocations("locations/toy_box_chests.json")
Tracker:AddLocations("locations/toy_box_events.json")
Tracker:AddLocations("locations/kingdom_of_corona_chests.json")
Tracker:AddLocations("locations/kingdom_of_corona_events.json")
Tracker:AddLocations("locations/monstropolis_chests.json")
Tracker:AddLocations("locations/monstropolis_events.json")
Tracker:AddLocations("locations/arendelle_chests.json")
Tracker:AddLocations("locations/arendelle_events.json")
Tracker:AddLocations("locations/the_caribbean_chests.json")
Tracker:AddLocations("locations/the_caribbean_events.json")
Tracker:AddLocations("locations/san_fransokyo_chests.json")
Tracker:AddLocations("locations/san_fransokyo_events.json")
-- "San Fransokyo Events" pin position differs between the light/dark map
-- images, so it's loaded from a variant-specific file and attached back to
-- the "San Fransokyo - Events" parent above via "parent".
if Tracker.ActiveVariantUID == "dark_vertical" or Tracker.ActiveVariantUID == "dark_horizontal" then
    Tracker:AddLocations("locations/san_fransokyo_events_dark.json")
else
    Tracker:AddLocations("locations/san_fransokyo_events_light.json")
end
Tracker:AddLocations("locations/keyblade_graveyard_chests.json")
Tracker:AddLocations("locations/keyblade_graveyard_events.json")
Tracker:AddLocations("locations/100_acre_wood.json")
Tracker:AddLocations("locations/dark_world.json")
Tracker:AddLocations("locations/re_mind.json")
Tracker:AddLocations("locations/level_ups.json")
Tracker:AddLocations("locations/battlegates.json")
Tracker:AddLocations("locations/lucky_emblems.json")
Tracker:AddLocations("locations/radiant_garden.json")
Tracker:AddLocations("locations/moogle_shop.json")
Tracker:AddLocations("locations/classic_kingdom.json")
Tracker:AddLocations("locations/olympus_coliseum.json")
Tracker:AddLocations("locations/melody_of_memory.json")
Tracker:AddLocations("locations/ingredients.json")
Tracker:AddLocations("locations/ingredients_plus.json")
Tracker:AddLocations("locations/flantastic_flans.json")
Tracker:AddLocations("locations/minigames.json")
Tracker:AddLocations("locations/photo_missions.json")
Tracker:AddLocations("locations/moogle_workshop.json")
